### ISSUE TITLE
UI - Make Chip Search More Responsive

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#109]
Chip Search acts funky when several chips are placed within the component

![](https://i.imgur.com/KcaNmKD.png)

- Consider making it more flexible by allowing the chip values to wrap to the next row.
- Consider making it work better on mobile using chip search wrapping

**Comment by benzap** [comment]
Still Issues with the search input breaking the responsive nature of the component.

![](https://i.imgur.com/24PF4Sy.png)

# Solutions
- Be aware of chip search dimensions and offer a vertical dropdown of currently active chips instead of displaying them as a horizontal listing.
- Alternative, include options to allow the chip search to be multiple lines

**Comment by benzap** [comment]
@jpmonettas  Files of Interest: [clj](https://github.com/district0x/ethlance/blob/newlance/src/ethlance/ui/component/search_input.cljs), [less](https://github.com/district0x/ethlance/blob/newlance/resources/public/less/component/search-input.less)

**Comment by jpmonettas** [comment]
With that fix it looks like 
![1594225324](https://user-images.githubusercontent.com/786299/86944725-843d2200-c11e-11ea-87d7-655f9fb0e5bd.png)
![1594225341](https://user-images.githubusercontent.com/786299/86944729-856e4f00-c11e-11ea-8b62-9b4e31c9aa47.png)
