### ISSUE TITLE
Jobs not loading when MetaMask is enabled

### ISSUE THREAD

**Issue by DarthVanger** [district0x/ethlance#125]
I can see jobs if I disable MetaMask Chrome extension

https://ethlance.com/#/find/work

But when MetaMask is enabled, jobs won't load.
There are errors in console:

<img width="1675" alt="ethlance jobs not loading" src="https://user-images.githubusercontent.com/6686679/67239460-e9999780-f457-11e9-8a9d-ec195d76b267.png">

It doesn't matter if I'm signed in:

<img width="1645" alt="meta-mask" src="https://user-images.githubusercontent.com/6686679/67239530-1188fb00-f458-11e9-9b75-a23b4f154c56.png">

Or logged out:

<img width="1627" alt="meta-mask-not-logged-in" src="https://user-images.githubusercontent.com/6686679/67240011-3893fc80-f459-11e9-9689-201494f3f58b.png">

`MetaMask` `v7.2.3`
`Chrome` `Version 77.0.3865.120 (Official Build) (64-bit)`
`MacOS` `Mojave 10.14.6 (18G103)`

<img width="419" alt="metamask-7-2-3" src="https://user-images.githubusercontent.com/6686679/67239576-29f91580-f458-11e9-939f-d0182283d669.png">

**Comment by benzap** [comment]
Hi @DarthVanger, can you clear your cache and try again. We made a deployment that includes changes that resolve a lot of issues.

**Comment by DarthVanger** [comment]
@benzap okay. Why can't you deploy code which clears the cache yourselves? :)
```
if (localStorage.somethingOld) {
   ....
}
```
Not all users are going to create an issue to find out that they need to clear cache...

**Comment by benzap** [comment]
Hard to say if your issue was due to cache or the set of changes we deployed yesterday, but i'm glad to hear it fixed your issue :)

Thanks for your feedback
