### ISSUE TITLE
General - Migrate Ethlance Tests from Travis to CircleCI

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#130]
Travis has been causing issues with testing, since it appears to lack certain criteria to reproduce builds from their end.

CircleCI uses self-contained docker images in a fashion that makes tests reproducible from any user's machine, making it suitable as a build tool, and makes testing and deployments more seamless.

**Comment by benzap** [comment]
@fbielejec showed interest in migrating to CircleCI

**Comment by madis** [comment]
Done
