### ISSUE TITLE
Ethereum contract (transaction) to create job still pending after 1 hour 37 min

### ISSUE THREAD

**Issue by DarthVanger** [district0x/ethlance#135]
I filled the new job form (https://ethlance.com/#/job/create) and clicked "publish".
In a popup I confirmed a metamask transaction.
The transaction is still shown as "pending" in metamask, after 1 hour 37 min.
Transaction on etherscan: https://etherscan.io/tx/0x98349d712c0f1275821ef99cfbcefc327c8032416c70da6e3e6f88f35beffac1
MetaMask screenshot:
<img width="366" alt="metamask-contract-ethlance" src="https://user-images.githubusercontent.com/6686679/68999255-ea8edf00-08c6-11ea-8cb0-edeb881bfba6.png">

I cleared the website data in the browser and tried to create the job for the 2nd time. The result is the same: transaction pending for an hour and still not finished.
2nd transaction on Etherscan:
https://etherscan.io/tx/0x6c0984e420eb8535dc1d5066a4eeedbf7fd7bd3eeed87569032ac61f2013ee6b

**Comment by DarthVanger** [comment]
Both transactions have finally succeded :)
Created another transaction to close one of the created job https://etherscan.io/tx/0x2bdefff39321f7b9921c37bb1eefda7eab39905ee8d044be9a7e346c7635afd5

Why did it take so long? Is it supposed to work this way? ... Have to wait for a day for each action? :)

**Comment by DarthVanger** [comment]
Transaction for closing the job went fine, succeeded in 5 minutes.

**Comment by benzap** [comment]
You probably witnessed some congestion, i'm glad to hear you fixed your issue 👍
