### ISSUE TITLE
Migrate to new web3

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#136]
Migrate server side into using our new cljs-web3 version

**Comment by jpmonettas** [comment]
This will have to wait until we figure out the UI using cljs-web3 and Server using cljs-web3-next problem.

The problem has to do with both projects using the same namespaces + UI and Server sources being in the same folder, so we can't compile.

**Comment by jpmonettas** [comment]
cljs-web3-next ended up renaming all namespaces, so this is implemented in https://github.com/district0x/ethlance/pull/138
