### ISSUE TITLE
Write a EthlanceBountyIssuer smart-contract

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#137]
According to readme at https://github.com/district0x/ethlance/tree/newlance. 
First paste https://github.com/Bounties-Network/StandardBounties/blob/master/contracts/StandardBounties.sol into the project.
Then write EthlanceBountyIssuer contract.

Part of this issue is to write deployer.

![image](https://user-images.githubusercontent.com/3857155/69073065-41c7b780-0a5f-11ea-9300-1abf1364a0e3.png)

**Comment by jpmonettas** [comment]
This was implemented in https://github.com/district0x/ethlance/commit/49754e7589534b6be915edc986738789cf68be66
