### ISSUE TITLE
UI - Implement Sign In Modal

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#153]
![](https://i.imgur.com/lxnoeF1.png)

**Comment by madvas** [comment]
[00_Modal.psd.zip](https://github.com/district0x/ethlance/files/3959036/00_Modal.psd.zip)

**Comment by benzap** [comment]
- Rename event handlers
  - `:sign-in` --> `:profile/sign-in`
- Delete subscription/modal.cljs file
