### ISSUE TITLE
Upload profile image is not implemented

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#177]
Should accept only square images with min. 256x256 and max 1024x1024

![image](https://user-images.githubusercontent.com/3857155/71440408-4d149f80-26fd-11ea-9015-842b8b849f03.png)

**Comment by benzap** [comment]
@jpmonettas Files of Interest: [clj](https://github.com/district0x/ethlance/blob/newlance/src/ethlance/ui/page/sign_up.cljs#L32), [less](https://github.com/district0x/ethlance/blob/newlance/resources/public/less/page/sign-up.less)
