### ISSUE TITLE
Add transition animation for feedbacks

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#196]
Implementation:
![feedback](https://user-images.githubusercontent.com/3857155/72338323-d4e73b80-36f6-11ea-80b4-e0c377551220.gif)

Design:
![feedback1](https://user-images.githubusercontent.com/3857155/72338405-fe07cc00-36f6-11ea-9ac3-be333afd402d.gif)

**Comment by jpmonettas** [comment]
This is not a animation detail, the carousel is not implemented.
