### ISSUE TITLE
UI does not detect changing of account in metamask

### ISSUE THREAD

**Issue by TripleSpeeder** [district0x/ethlance#21]
UI does not recognize if I select another account in metamask. You need to manually reload the page so it picks up the new selected account.

Metamask only ever exposes one account (`web3.eth.accounts[0]`) to the dapp. Currently there is no nice way of getting a callback or similar when the account changes. Instead a dapp needs to watch `accounts[0]` for changes. Code sample from the [metamask developer faq](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#ear-listening-for-selected-account-changes):
```javascript
var account = web3.eth.accounts[0];
var accountInterval = setInterval(function() {
  if (web3.eth.accounts[0] !== account) {
    account = web3.eth.accounts[0];
    updateInterface();
  }
}, 100);```

**Comment by benzap** [comment]
This has been fixed in #22
