### ISSUE TITLE
Support user owned NFTs as avatars

### ISSUE THREAD

**Issue by cliffhall** [district0x/ethlance#226]
Ethereum users who collect NFTs are increasingly interested in using them for identity purposes. For instance:

![365EE394-ACAC-4DDD-8B62-6A5E942D47CF](https://user-images.githubusercontent.com/871933/75788078-b3d5bb00-5d35-11ea-8c5a-8a0571af07fc.jpeg)

https://twitter.com/ethlance/status/1234730022063280128?s=21

I am the developer of the Avastars project mentioned in that tweet, and we store our images on-chain. They’re available with a single, free, view call to our contract. While most other projects (like CryptoKitties) store their art off-chain, they should be viable as avatars, and I can help you suss out how to support many of them as well.

Feel free to ping me if you decide to move forward with this, I’ll be glad to help.

**Comment by rhyolight** [comment]
I think this is a great idea.

**Comment by Tweetie-Pie** [comment]
Great idea

**Comment by eltoro121** [comment]
Let’s get this going.

**Comment by AlanFalcon** [comment]
I'd really love to be able to use an NFT that I own as my avatar!
