### ISSUE TITLE
Improvement: Add support for the Ledger Nano S

### ISSUE THREAD

**Issue by Techwolf12** [district0x/ethlance#30]
Hi!

It would be great if there would be support for the Ledger Nano S hardware wallet, you can find JS examples in the MyEtherWallet repo

**Comment by benzap** [comment]
Hey @Techwolf12 , You can link hardware wallets to the [metamask](https://metamask.io/). I believe all of the major hardware wallet vendors are supported (Ledger, Trezor, etc)

Thanks for your feedback!
