### ISSUE TITLE
Jobs list won't load

### ISSUE THREAD

**Issue by DarthVanger** [district0x/ethlance#306]
Jobs list won't load after I login with MetaMask.
There are some errors in the console.

Screenshot:

![image](https://user-images.githubusercontent.com/6686679/105407888-ee3e9400-5c36-11eb-8869-d8164433bb6a.png)

**Comment by mahesh3396** [comment]
Maybe as per my view, the API key provided with infura exceeded its limit. Need to change API key or update the plan of API to increase the limit of requests.

**Comment by let4be** [comment]
Same error... was really curious checking this out

**Comment by let4be** [comment]
This is needed very much, especially now in the events of such marketplaces as upwork throwing their freelancers face down into dirt for nothing, just because they happened to live in Russia

**Comment by DarthVanger** [comment]
@let4be It works for me now. Try clearing your `localStorage` and `cookies`.

**Comment by DarthVanger** [comment]
@let4be P.S. The platform is not very active currently though :(
The last job was posted on Dec 2020.
I believe this is due to the high gas prices, for example I have to pay $14 only to post a job.
In 2021 Ethereum price jumped and maybe that's when ppl stopped using this great app :(

**Comment by let4be** [comment]
Works! Amazing app
Let's hope eth 2.0 helps to bring costs down :)

**Comment by let4be** [comment]
It's broken again btw...
I checked console logs and it's the API key(daily limit of requests probably), this needs an upgrade or something because as-is it's just a toy nobody can even try to use

I'm trying to understand where are the funds taken from to run this project, is it somehow funded by district0x and sale of tokens?

**Comment by DarthVanger** [comment]
@let4be Yeah I think it's funded through distric0x. On [the distrcict0x registry page](https://registry.district0x.io/) you can see Ethlance had `240,379.1 DNT` staked, which is now $16k :) (DNT = 0.07 USD)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/6686679/159185290-fafc2f8e-c434-46e7-8cba-ced220a0e0f3.png">

As far as I can see the last commit in the ethlance repo was on Nov 2021, so the things doesn't look too good :(

**Comment by let4be** [comment]
I remember reading somewhere about an incentive to move this to layer 2 like Polygon... has there been any attempts/talks?
I also do not understand what is the lifecycle of the project on district0x after it gets funded...

**Comment by DarthVanger** [comment]
@let4be I don't know 🤷 
On the [main page](https://district0x.io/) there are links to blog, twitter, and an education portal.
It seems like they're focused on the MemeFactory right now and that it's going to use Polygon indeed.
As for the Ethlance I don't see any updates after [the tweet](https://twitter.com/ethlance/status/1380626573779419139) on Apr 2021 about "Ethlance getting a makeover".
Btw it turns out on the [district0x discord server](https://discord.com/invite/sS2AWYm) there is a `Ethlance -> -job-board` channel. Not much activity there as well, but I can see 2 recent posts with jobs.

**Comment by hiro00125** [comment]
I've just joined with metamask, but I can't see any jobs in the "Find Work".
