### ISSUE TITLE
When I hit send I am faced with an error message

### ISSUE THREAD

**Issue by LucaSolari** [district0x/ethlance#34]

**Comment by madvas** [comment]
Can you post the error?

**Comment by LucaSolari** [comment]
![img_0647](https://user-images.githubusercontent.com/34396007/33795652-dfee2272-dce5-11e7-9ab9-5914ff50ea1e.JPG)

**Comment by madvas** [comment]
oh, you need to increase gas price when you're confirming metamask transaction. Network is currently terribly clogged. Or wait with this for later, if you don't want to pay more for the transaction.

**Comment by LucaSolari** [comment]
Thank YOu! I am a newcomer

**Comment by madvas** [comment]
yeah, this is not best time to start with ethereum. There's currently 22k transactions pending https://etherscan.io/txsPending
