### ISSUE TITLE
How you make money

### ISSUE THREAD

**Issue by inwardmovement** [district0x/ethlance#35]
Hi,

Just wanted to know how you make money with Ethlance ? 
Is it a "pure altruism-based" application ?

**Comment by madvas** [comment]
Ethlance doesn't make any money yet, but we plan to do major remake of the website in 2018, which will include bunch of new features, monetisation model, new looks and decentralised governance. Stay tuned for that ;)

**Comment by benzap** [comment]
Question answered by Matus :)
