### ISSUE TITLE
Failed job posting due to gas is not explained

### ISSUE THREAD

**Issue by rememberlenny** [district0x/ethlance#36]
# What

I tried to make a job posting, but was unsuccessful. I was redirected to Job page without explanation. I thought I was charged ETH for the transaction, but the contract never appeared.

# Hypothesis

When I initially paid for the contract, the gas was too low, so the contract was unsuccessful. The 
"create job" page was stuck in a "loading" state after the failed contract, so I refreshed the page. After refreshing, I re-entered the information and then submitted. After adjusting the gas, I was successfully redirected to the "My jobs" page.

# Issue

The contract that was successful, but didnt result in a job can be seen with this transaction: [0x7f442b0d4d330023e907ed7fdca93c858aa21c476c5f29db7094617cf7385662](https://etherscan.io/tx/0x7f442b0d4d330023e907ed7fdca93c858aa21c476c5f29db7094617cf7385662).

The contract that was failed, and forced me to restart can be seen with this transaction.
[0x0bc10f232919ba1e6f8c75d7f458ca83a4db5459a5d805739a22b63b6afe0458](https://etherscan.io/tx/0x0bc10f232919ba1e6f8c75d7f458ca83a4db5459a5d805739a22b63b6afe0458)

# Actual issue

As seen in the first contract link, the failed contract was "Out of gas". This was never addressed on the front-end and led to a confusing UI.

**Comment by benzap** [comment]
Hey @rememberlenny,

In the ethlance redesign, a lot of this functionality will be streamlined to provide a better user experience. I would like to point out that I love your issue template, i'm assuming you work in QA :)

Cheers, and thanks for bringing this to our attention
