### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by crypdick** [district0x/ethlance#37]
I think ethlance is a shining example of a decentralized market platform. It is inspiring me to try to create one of my own, but unfortunately I'm having a hard time learning from the codebase because of lack of comments.

**Comment by benzap** [comment]
Hey @crypdick ,

We're currently in the process of redesigning ethlance. The implementation of the new design isn't complete, but we're going to make a conscious effort to include appropriate documentation.

Thank you for your feedback!
