### ISSUE TITLE
We need to add AI related skills

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#379]
The skill list needs to be updated to contain AI related technologies, stable diffusion, chatGPT, etc. there's many, we should find some list somewhere on the web. 

![image](https://github.com/district0x/ethlance/assets/3857155/98d6b9cd-d56e-419a-8994-e6fe524ce6af)

**Comment by madis** [comment]
I'd like to elaborate on this requirement a bit. Currently, if the skill is not listed, user can enter new skill and it will be stored to the DB. Next is an image for `jobskills`, where I entered `Chat GPT`
![image](https://github.com/district0x/ethlance/assets/674621/6b1f39d4-2840-4fe8-abcd-413ebf703423)

The same happens for the skills on user's profile page.
But these get saved in their respective tables and associated with the particular job or user type (e.g. `jobskill` `arbiterskill` or `candidateskill`) and thus don't appear in the future dropdowns.

I'm not sure what would be the preferred behaviour here - each have their pros & cons:
1. In case the manually added new skills should show up in the future dropdowns (e.g. during job creation), then the list can get overcrowded - people can add new skills, many of which can be similar and redundant or even spam.
  - that would talk against filling the list with user-added skills (in addition to the hard-coded/default skills)
2. Also currently the manually added skills are not normalized (in DB terms, they're stored in separate tables, no unique PK), meaning that if user sets up their profile with `AI mastermind` then when searching the job, it wouldn't show up in the autocomplete dropdown and vice versa (e.g. searching candidate by skill that the job requires)

You can add your comments here of the preferred direction or this comment can serve for discussion during our next call
