### ISSUE TITLE
Homepage is broken on mobile

### ISSUE THREAD

**Issue by derekchiang** [district0x/ethlance#38]
Here are some screenshots:

Toshi:

![ethlance_toshi](https://user-images.githubusercontent.com/1535686/37239213-5067a788-23ec-11e8-8f6f-a5ffdf6b54a1.png)

Cipher:

![ethlance_cipher](https://user-images.githubusercontent.com/1535686/37239215-5a26b002-23ec-11e8-95cc-7d53fe5912d4.png)

Looks fine on Status though:

![ethlance_status](https://user-images.githubusercontent.com/1535686/37239217-5f3adcc6-23ec-11e8-9b98-28774eb780e1.png)

**Comment by benzap** [comment]
This happens at page widths < 230px, which is a small enough dimension that it can be deemed almost uncommon. Will look into making such accommodations in the rework, so your feedback is appreciated
