### ISSUE TITLE
Languages search should search by the beginning of the word

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#383]
This is weird UX, I type in en and it shows me different languages than english

![image](https://github.com/district0x/ethlance/assets/3857155/dd862eef-2037-46b1-8a21-c5895cdc94b5)

**Comment by madis** [comment]
I used https://github.com/wilkerlucio/fuzzy-cljs/blob/master/src/main/com/wsscode/fuzzy.cljs for this and I think the results are more useful than just plain `clojure.string/stars-with?`

[Screencast from 11.03.2024 18:17:07.webm](https://github.com/district0x/ethlance/assets/674621/b0ec5434-0609-4adf-b27f-2ce7360f7623)
