### ISSUE TITLE
Cannot save candidate profile, no reason given

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#391]
🤷‍♂️

![image](https://github.com/district0x/ethlance/assets/3857155/94b1d787-a5f5-41eb-8a32-5a8683b99830)

**Comment by madis** [comment]
I was unable to reproduce it immediately. Will add debug logging around the validation of the form to figure out why

**Comment by madvas** [comment]
So I figured out the issue was that I tried to upload .webp image format. We should support it. But also, the profile image should not be required to submit a profile.

**Comment by madis** [comment]
Added the `.webp` support. Also profile image isn't required https://github.com/district0x/ethlance/blob/newlance/shared/src/ethlance/shared/spec.cljs#L81-L110
