### ISSUE TITLE
Inviting arbitrer shows crazy gas price

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#393]
Too much gas, it actually didn't eat that much gas when I confirmed, so gas limit is probably set to very large amount for now reason.

![image](https://github.com/district0x/ethlance/assets/3857155/3338a29c-03d7-4c73-99d2-71fbe32f7872)

**Comment by madis** [comment]
Currently the gas amount is set to a fixed amount in multiple places. When the `:gas` parameter is not sent, MetaMask does estimation automatically. Would it be advisable to do it that way in all the places? (Like done in e4b53231c1cc1ec3e3c35aca9fca8fc673babc24)

**Comment by madis** [comment]
Tried it in QA, the MetaMask estimation worked: 
![image](https://github.com/district0x/ethlance/assets/674621/f053c727-ec37-4f93-8e5a-54e24b62a967)
