### ISSUE TITLE
Improve hyperlink unfurls

### ISSUE THREAD

**Issue by Alexand0x** [district0x/ethlance#40]
When posting job links (e.g. https://ethlance.com/#/job/354) into clients like Slack, Discord, etc. the unfurl that is displayed only contains generic information for the Ethlance website.

At minimum, we should change these unfurl patterns to accommodate:

- Job postings, including the title of the job post, truncated description, and possibly the employers logo. Any other relevant metadata that can be formatted to fit is welcom.

As a bonus, we should also accommodate:
- Freelancer profiles, including their headshot and profile description and any other relevant metadata (join date, rating?)
- Employer profiles, including their logo and a description of the company

**Comment by madis** [comment]
Fixed already in newlance
