### ISSUE TITLE
Jobs page should show loading icon when loading jobs

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#407]
It shows there are no jobs until jobs are loaded. There should be loading icon instead. 

![image](https://github.com/district0x/ethlance/assets/3857155/5be1f17f-2b34-4f30-b7cd-2cd9c19aba40)

**Comment by madvas** [comment]
Apply for other search pages as well

**Comment by madis** [comment]
Fix looks like this

https://github.com/district0x/ethlance/assets/674621/695a5a12-0436-4b71-89cf-8b299749c635
