### ISSUE TITLE
Limit number of characters shown in job search page

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#408]
This is obviously too long, it should cut it off at around half length of this 

![image](https://github.com/district0x/ethlance/assets/3857155/1dda208e-92f7-457b-995e-841d4467fe3f)

**Comment by madis** [comment]
Truncated at 900 chars and ended with `...` in case of being truncated
![image](https://github.com/district0x/ethlance/assets/674621/ffc72936-28ad-4a8b-9e5d-6a42bac55cfa)
