### ISSUE TITLE
After switching addresses with metamask, it doesn't show balance as when actually refreshed

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#410]
It shows balance like this if I just switch metamask address and click Sign, without refreshing

![image](https://github.com/district0x/ethlance/assets/3857155/0e17e25b-5abb-4be3-96b0-a7aec8409af8)

After I refresh, it shows like this: 
![image](https://github.com/district0x/ethlance/assets/3857155/adf3c3f4-0710-4f87-9d68-8f8f8e6e50db)

**Comment by madis** [comment]
For reference where it's happening https://github.com/district0x/ethlance/issues/404#issuecomment-2081708076
