### ISSUE TITLE
accepting job proposal throws internal server error

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#413]
![image](https://github.com/district0x/ethlance/assets/3857155/6a2fabda-5ea3-4029-8cc5-3c6c5ce774eb)

**Comment by madis** [comment]
I suspect it was either a temporary issue w/ IPFS or the syncer issue. Just completed a successful flow `create job -> add proposal -> accept proposal`
[Screencast from 10.05.2024 19:00:58.webm](https://github.com/district0x/ethlance/assets/674621/12afc7cc-4beb-425b-aba5-9178bcdcf53a)

**Comment by madis** [comment]
Closing it for now as it seems to be working
