### ISSUE TITLE
Inconsistent alignment of numbers at new invoice page

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#416]
This doesn't look good and it's also confusing, because when I click closer to $ symbol it doesn't focus the input. Input field should go closer to "$" and "ETH". 

![image](https://github.com/district0x/ethlance/assets/3857155/5ac80e9f-97c5-418c-b9c5-6419509bf308)

**Comment by madis** [comment]
Fix behaviour can be seen here:

https://github.com/district0x/ethlance/assets/674621/6541ad8e-2f53-4a88-84fd-3b79efd8d90f
