### ISSUE TITLE
Resolving dispute form needs improvements

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#418]
![image](https://github.com/district0x/ethlance/assets/3857155/ef7b4b73-af7b-4378-960a-aeca9aacdb9e)

1. It doesn't set default value. Slider is in the middle, but values are not set. 
2. First part of text should be on separate line. Slider should be on separate line. Last part of text should be on separate line. 
3. Numbers in slider should be in regular horizontal position.

**Comment by madis** [comment]
The fix looks like this:
![image](https://github.com/district0x/ethlance/assets/674621/ba547d27-1cea-4316-bfa4-13951bb2b37d)
