### ISSUE TITLE
After leaving feedback for arbitrer, it didn't show it until I refreshed page

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#421]
Don't have screenshot, but after I submitted feedback for arbitrer, it reloaded data, but feedback was not there until I refreshed. Also, there's no loading indicator while data is being reloaded, nor disabled submit button, which is confusing.

**Comment by madvas** [comment]
Also, when arbitrer left feedback for employer, first time I clicked, it refreshed but feedback was not there. When I clicked second time, it refresh and feedback was there.

**Comment by madis** [comment]
Notes from a call:
Job contract page: when sending a message, the page shouldn't scroll to top
  - instead the newly added message should be appended to the bottom

**Comment by madis** [comment]
This seems to have been a one-off issue as I can't reproduce it locally or in QA. Closing until new appearance.
