### ISSUE TITLE
Creating job with ERC721 throws console error

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#430]
(I minted ERC721 beforehand)

![image](https://github.com/district0x/ethlance/assets/3857155/e2ca6f8f-d1b6-44c0-a3e6-d9247d449b72)

**Comment by madis** [comment]
It was caused by the `value` field of `OfferedValue` being empty. For ERC721 it's always 1 (token amount). Fixed it.
![image](https://github.com/district0x/ethlance/assets/674621/177a4b96-f6fc-481f-8532-bca0b39cbd1a)
