### ISSUE TITLE
New Ethlance home page changes

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#50]
1. Add third button Become an Arbiter
![image](https://user-images.githubusercontent.com/3857155/56107883-e71f2800-5f72-11e9-8ed6-9c63cea99971.png)

2. Let's change "No restrictions and free membership" to "No restrictions, no fees and free membership" (icon might need some update as well). And then we'll replace "0% service fees" with "Decentralised dispute resolution, anyone can become an arbiter" (new icon will be needed)
![image](https://user-images.githubusercontent.com/3857155/56108130-3fa2f500-5f74-11e9-895b-49e823f5347d.png)

3. Add third tab "Arbiter" with following steps: Complete your profile, Receive invitation for job supervision, Investigate the problem, Resolve the dispute, Receive Ether, Leave feedback
![image](https://user-images.githubusercontent.com/3857155/56108560-b93be280-5f76-11e9-8aa6-fcda22cbacde.png)

4. Add third button Become an Arbiter
![image](https://user-images.githubusercontent.com/3857155/56108930-91e61500-5f78-11e9-9fbf-0ff80e891c39.png)

**Comment by benzap** [comment]
This was added in latest ethlance designs
