### ISSUE TITLE
Ethlance can only run with Privacy Mode turned off. 

### ISSUE THREAD

**Issue by Bradymck** [district0x/ethlance#51]
The new Metamask feature 'Privacy Mode' needs to be disabled before people can use Ethlance. THis is a privacy issue for people and we should add the correct permission prompt like other Dapps.

**Comment by benzap** [comment]
Not able to reproduce, since i'm seeing the privacy-mode prompt

![](https://i.imgur.com/M5BlqYA.png)

Steps I took:
1. Logged out
2. Refreshed page
3. Was prompted by Metamask to enter my password, entered my password
4. The given screen was shown, asking for permissions to access my accounts

Is there another prompt that is supposed to be showing? @Bradymck

**Comment by Bradymck** [comment]
This isn't showing for several people. I have had them try multiple browsers too. It may be an operating system issue, I will follow up and see.

**Comment by benzap** [comment]
I only tested it within Ubuntu 18.04, but there are definitely some issues showing up for the other ticket #52 which might include a vbump. This might hopefully just fix this issue as well

**Comment by Bradymck** [comment]
FYI, this is happening in Name Bazaar too, had several reports that disabling privacy mode lets them use it.

**Comment by benzap** [comment]
@Bradymck i'm jumping back on this, what kind of things do they see when privacy mode is turned on? Does it just not allow them to connect whatsoever? When they connect, does it show the prompt, but upon accepting the connection, do their accounts just simply not appear to connect within the dapp itself? ie. top right header bar goes from 'No Connection' -> '0x???????????' 

The important detail is whether they see the prompt at all when starting the dapp. I might have an idea of what's going on if that's the case.

**Comment by Bradymck** [comment]
Correct, it's like you aren't logged into metamask at all. I get this issue too. Windows 10, Chrome, Newest version of Metamask. Shows not connected and no wallet address in top left. Turn off privacy mode in Metamask and it connects right away. All our apps are doing this

**Comment by Bradymck** [comment]
No prompt at all when you first go to the site. It should pop up right away but Metamask does nothing until you turn of privacy mode.

**Comment by lukas2005** [comment]
It appears that i have the same issue

**Comment by kaptainzero** [comment]
I still have the same issue, extension downloaded from chrome store.

**Comment by Bradymck** [comment]
@kaptainzero We have this fixed and currently working on the Redesign of Ethlance. Stay tuned to our [blog ](https://blog.district0x.io/)and [live streams](https://www.twitch.tv/district0x) for updates.
