### ISSUE TITLE
Formatting of Solidity looks weird in my IDE

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#54]
Formatting in my IDE looks quite broken:

![image](https://user-images.githubusercontent.com/3857155/56645843-a1680b00-66a8-11e9-9250-d64bf45e8056.png)

![image](https://user-images.githubusercontent.com/3857155/56645852-a7f68280-66a8-11e9-980b-826b235f125f.png)

Although I see, on Github it look ok. Do you have any idea what might be the problem? Besides, we wanna do 2 spaces indent. 

![image](https://user-images.githubusercontent.com/3857155/56645953-d4aa9a00-66a8-11e9-8ef7-5c13b216ad21.png)

**Comment by benzap** [comment]
Looks like it's because you have tabs set to 0 spaces in your IDE

![](https://i.imgur.com/2EtlC3p.png)

Seems we've hit a tabs versus spaces war :)

I'll untabify everything, and I think there's a way I can configure solidity-mode to always use spaces, so we can avoid this issue

**Comment by benzap** [comment]
Latest commit untabify'd everything, should look fine now
