### ISSUE TITLE
Move away from using generic event fireEvent

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#55]
Edit contracts in a way that we'll stop using generic fireEvent https://github.com/district0x/ethlance/blob/bce6e377f7a997ab8c5cb6c737194cf6b06a1f80/resources/public/contracts/src/EthlanceRegistry.sol#L158 and instead for each event we'll have separate definition. Similarly like we did for MemeFactory https://github.com/district0x/memefactory/blob/6951aa05c6882424f4552d408551157c1bbe0517/contracts/Registry.sol#L27-L38

**Comment by benzap** [comment]
Not relevant anymore
