### ISSUE TITLE
Move contract data from state into events/IPFS

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#56]
In many places, such as: 
https://github.com/district0x/ethlance/blob/bce6e377f7a997ab8c5cb6c737194cf6b06a1f80/resources/public/contracts/src/EthlanceUser.sol#L160-L162
https://github.com/district0x/ethlance/blob/bce6e377f7a997ab8c5cb6c737194cf6b06a1f80/resources/public/contracts/src/EthlanceJobStore.sol#L100-L105
https://github.com/district0x/ethlance/blob/bce6e377f7a997ab8c5cb6c737194cf6b06a1f80/resources/public/contracts/src/EthlanceInvoice.sol#L61-L63
https://github.com/district0x/ethlance/blob/bce6e377f7a997ab8c5cb6c737194cf6b06a1f80/resources/public/contracts/src/EthlanceFeedback.sol#L161-L168

We're storing data in smart-contract state unnecessarily, because it's nowhere used for trustless logic within smart-contracts. All data that doesn't need to be accessed from other smart-contracts, should be passed to an event or stored as IPFS hash and server will reconstruct it from there. This way lot of gas will be saved. You can actually combine event and IPFS approach into the one, by not even storing IPFS hash in smart-contract, but just passing it into event. You can learn more about this approach here: 
https://medium.com/@childsmaidment/stateless-smart-contracts-21830b0cd1b6

**Comment by benzap** [comment]
Not relevant anymore
