### ISSUE TITLE
 I only get a "No accounts connected" [using Brave Browser + MetaMask]

### ISSUE THREAD

**Issue by lukas2005** [district0x/ethlance#62]
I can't create an account on  the page. I am using MetaMask + Brave Browser Beta (v0.62.37)

**Comment by lukas2005** [comment]
?

**Comment by sshelton76** [comment]
MetaMask recently implemented EIP1102
This means that ETHLance will need to update in order for metamask to work out of the box.
In the meantime, you need to go into your metamask settings and disable privacy mode and refresh the page.  Make sure you re-enable it when you're done with ETHLance.
https://medium.com/metamask/eip-1102-preparing-your-dapp-5027b2c9ed76 
https://medium.com/metamask/introducing-privacy-mode-42549d4870fa

**Comment by Bild96** [comment]
Thank you for the lats information regarding MetaMask and Ethlance

**Comment by benzap** [comment]
This has been fixed in the latest deployment. There were changes that we pulled over from memefactory that we failed to replicate correctly, and tests have shown that the changes related to EIP1102 are fixed within ethlance. Place open another ticket if the problem persists.
