### ISSUE TITLE
UI - Implement Home Page (Splash Page)

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#63]
Develop Splash page for both desktop and mobile (responsive design)

# Desktop Page Previews
![](https://i.imgur.com/2llySWR.png)
![](https://i.imgur.com/2cP4g9B.png)
![](https://i.imgur.com/b43bLKH.png)
...

# Mobile Page Previews
![](https://i.imgur.com/uoFWaqE.png)
![](https://i.imgur.com/5JttlSs.png)

**Comment by madvas** [comment]
### Desktop

* Missing  anti-aliasing and other font smoothing effects, throughout the whole app. As in designs:
![image](https://user-images.githubusercontent.com/3857155/66139321-6dffb400-e62a-11e9-9ff2-b7f1135c8bd9.png)
* Buttons should have larger padding
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66139506-c5058900-e62a-11e9-8ffb-3a44a821e502.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66139521-cc2c9700-e62a-11e9-93b9-d546d0203939.png)

* "Participate..." should be of gray color
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66139688-0f870580-e62b-11e9-80d9-bf157413a827.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66139614-efefdd00-e62a-11e9-9982-026948fb902c.png)

* While panels should be lower height
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66139896-642a8080-e62b-11e9-9117-f888e7c0e652.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66139914-6a206180-e62b-11e9-9485-0e15a5ca8668.png)

* Tabs have inverted styling compared to designs. Selected one should be purple:
* Tabs should have less width and closer to each other
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66140006-90460180-e62b-11e9-9916-e086bd6540a4.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66140028-976d0f80-e62b-11e9-8b6b-b521e17ff31f.png)

* Missing Ethlance logo in the footer: 
Impl:
![image](https://user-images.githubusercontent.com/3857155/66140159-d13e1600-e62b-11e9-9aa0-2d171443bc70.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66140179-de5b0500-e62b-11e9-9ca3-26297929f5ef.png)

* Email input is not correctly styled
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66140205-e7e46d00-e62b-11e9-85b1-9deb6a666b2d.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66140221-ee72e480-e62b-11e9-9706-5b196b6f5680.png)

* Underline should disappear when scrolling
Impl:
![image](https://user-images.githubusercontent.com/3857155/66140416-427dc900-e62c-11e9-8845-fff5c6687b26.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66140423-4873aa00-e62c-11e9-8ee4-9cbeebab70c6.png)

### IPad portrait
* White panels are overflowing
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66140539-7fe25680-e62c-11e9-8581-e1e46eb8fe22.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66140585-9092cc80-e62c-11e9-8b8b-7d39bcb797fc.png)

### IPhone portrait
* Text should be centred with more padding towards sides
Impl:
![image](https://user-images.githubusercontent.com/3857155/66141367-c3899000-e62d-11e9-95a8-43772572fff9.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66141395-d00de880-e62d-11e9-8afe-a8ec86aa7eb6.png)

**Comment by benzap** [comment]
Closing tickets that were refined, having a hard time keeping track
