### ISSUE TITLE
UI - Implement Invoice Detail Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#66]
# Desktop Preview
![](https://i.imgur.com/UDBxUIz.png)

# Mobile Preview
![](https://i.imgur.com/lAALI9R.png)

**Comment by madvas** [comment]
* Layout should be wider
Impl:
![image](https://user-images.githubusercontent.com/3857155/66216792-4f63f080-e6f0-11e9-882a-de44b985e523.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66216822-5f7bd000-e6f0-11e9-8697-a61af7ce8125.png)

* Pending label should be narrower
Impl:
![image](https://user-images.githubusercontent.com/3857155/66216892-7c180800-e6f0-11e9-89e3-2837d463e34b.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66216923-8fc36e80-e6f0-11e9-968e-0c5edbe1e6c5.png)

**Comment by benzap** [comment]
Closing tickets that were refined, having a hard time keeping track
