### ISSUE TITLE
UI - Implement Job Contract Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#67]
# Desktop Preview
![](https://i.imgur.com/JKoESWr.png)

# Mobile Preview
![](https://i.imgur.com/Ja7nrTm.png)

**Comment by benzap** [comment]
Merged in #87

**Comment by madvas** [comment]
* Whole layout should be wider
* Headline should have less font-weight and more font-size
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714807-bfa3fd80-ede5-11e9-8566-206653cb3c68.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714813-d4809100-ede5-11e9-961b-10b6cba6ef75.png)

* Tabs should be spread throughout the whole width of underlying white panel
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714830-101b5b00-ede6-11e9-9be0-a9b1b3a3cffd.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714842-2c1efc80-ede6-11e9-9382-bde2c6b5d3d4.png)

* There should be no placeholder in this textarea
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714844-3ccf7280-ede6-11e9-8ef1-0616c9949fba.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714847-4e187f00-ede6-11e9-899d-614d4bc0feba.png)

* Leave feedback is missing stars and note at the bottom
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714851-5c669b00-ede6-11e9-8cc7-24cf44c89fd1.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714863-7902d300-ede6-11e9-906f-cf04ee5f34d7.png)

**Comment by benzap** [comment]
Closing to keep track of finished work
