### ISSUE TITLE
UI - Implement Job Detail Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#68]
# Desktop Preview
![](https://i.imgur.com/dSxhRTs.png)

# Mobile Preview
![](https://i.imgur.com/CabO0MX.png)

**Comment by madvas** [comment]
* Whole layout should be wider
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714910-2b3a9a80-ede7-11e9-8d22-a96ecd5da2e1.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714917-3c83a700-ede7-11e9-9b62-78d2715d14f7.png)

* Font size should be smaller
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714941-8bc9d780-ede7-11e9-9bf6-009721d3e076.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714946-92f0e580-ede7-11e9-8268-1c7a2e4de473.png)

* Background of white panel gets blue as I scroll down
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714952-9dab7a80-ede7-11e9-9eab-7a2eac141476.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714957-ac922d00-ede7-11e9-9c0a-f99512e7a466.png)


* Number should be smaller and different font-family and font color
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714960-b9168580-ede7-11e9-99b3-2a0305555811.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714969-d4819080-ede7-11e9-95e9-5cb9ab53953d.png)

* Pagination buttons should be smaller with smaller icons inside
Impl:
![image](https://user-images.githubusercontent.com/3857155/66714985-05fa5c00-ede8-11e9-85be-bad805a733de.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66714991-16123b80-ede8-11e9-873f-2b1b3f31d5db.png)

* All white panels have some light inset shadow
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715010-507bd880-ede8-11e9-9609-0d925f5aacd3.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715007-3b06ae80-ede8-11e9-9841-249b0b23342e.png)


### Iphone X portrait
* Layout is broken
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715023-80c37700-ede8-11e9-8525-81d847957959.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715026-8a4cdf00-ede8-11e9-9f55-5166fbf6201d.png)

* Font size should be larger
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715030-93d64700-ede8-11e9-93f9-9739f4989af6.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715032-a2bcf980-ede8-11e9-964d-5eb62c8abb46.png)

* Side scrolling is not implemented
* Pagination buttons should be smaller and aligned right
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715039-cc762080-ede8-11e9-9685-0f90d73408a0.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715045-de57c380-ede8-11e9-8212-853e6dddb17c.png)

* Input is disabled and missing bottom border
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715079-3262a800-ede9-11e9-95cc-b5dd64af7249.png)

* Placeholder should be different color
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715090-4ad2c280-ede9-11e9-9a89-bc258d735b1f.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715109-7786da00-ede9-11e9-8023-2e85d56a69ec.png)

* Account balance and account select are not styled
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715214-ad788e00-edea-11e9-97ad-fc7769a89bf0.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715219-bec19a80-edea-11e9-95f7-e8b46faa5f84.png)

**Comment by benzap** [comment]
Refinement finished, closing to manage tasks
