### ISSUE TITLE
UI - Implement Jobs Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#69]
# Desktop Preview
![](https://i.imgur.com/rpkIpvU.png)

# Mobile Preview
![](https://i.imgur.com/C3n8daC.png)

**Comment by madvas** [comment]
* Layout should be stretched to a full width
Impl:
![image](https://user-images.githubusercontent.com/3857155/66712132-58c11d00-edc2-11e9-9247-0edb5bbaee9c.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66712136-670f3900-edc2-11e9-99a3-a4272a735823.png)

* Placeholders should be white color
* Missing Number of Feedbacks input
Impl:
![image](https://user-images.githubusercontent.com/3857155/66712142-83ab7100-edc2-11e9-8348-0fe6c6d37c7c.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66712264-2e705f00-edc4-11e9-8686-09cdb5fc5cbd.png)


* Missing country select field
Impl:
![image](https://user-images.githubusercontent.com/3857155/66712251-f6691c00-edc3-11e9-86d1-31ee391af847.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66712258-1a2c6200-edc4-11e9-89fe-b7b0841c2675.png)

**Comment by benzap** [comment]
Closing to keep track of tasks
