### ISSUE TITLE
UI - Implement My Contracts Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#70]
# Desktop Preview
![](https://i.imgur.com/7PX2jHG.png)

# Mobile Preview
![](https://i.imgur.com/JjSGLJ3.png)

**Comment by benzap** [comment]
This is related to #71 and #72, so those can be closed and focused within this issue

**Comment by madvas** [comment]
This page doesn't work
![image](https://user-images.githubusercontent.com/3857155/66715266-75257f80-edeb-11e9-920f-47df3e016ff7.png)

![image](https://user-images.githubusercontent.com/3857155/66715269-7bb3f700-edeb-11e9-8104-7b8f5fe33eda.png)

**Comment by madvas** [comment]
* Layout should be wider
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715309-2af0ce00-edec-11e9-84c8-81272c2421be.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715326-4d82e700-edec-11e9-947e-85944c2488f9.png)


* Pagination buttons should be smaller with smaller icons
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715319-3f34cb00-edec-11e9-824d-093520701f8c.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715332-5c699980-edec-11e9-9df0-d868aca60f5c.png)

### Iphone X portrait
* Layout is broken
* Select field is missing value
* Side menu is missing
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715373-ca15c580-edec-11e9-8910-1d3bb9b54dcc.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715378-d6018780-edec-11e9-89b5-8ff08ae932a9.png)

* Side scrolling is not implemented
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715395-18c35f80-eded-11e9-91f1-06a9bafa00f6.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715393-0b0dda00-eded-11e9-9b87-d7cd917a5fb9.png)

**Comment by benzap** [comment]
Layout is broken due to table component being unresponsive, this will be addressed in #107

**Comment by benzap** [comment]
Closing to keep track of finished work
