### ISSUE TITLE
UI - Implement New Invoice Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#74]
# Desktop Preview
![](https://i.imgur.com/csOUNHm.png)

# Mobile Preview
![](https://i.imgur.com/9oXHwcE.png)

**Comment by madvas** [comment]
* Layout should be wider
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715539-d6028700-edee-11e9-89c2-264441a8fa7f.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715557-fa5e6380-edee-11e9-9d0d-152b482d3ae9.png)


* Job should be select field
* Values shouldn't have different color than rest of the text
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715550-f2062880-edee-11e9-925d-77c0b02b1605.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715594-5d4ffa80-edef-11e9-921f-a3d38c5f05c2.png)

* Textarea should have different color and font size
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715599-6640cc00-edef-11e9-8dfe-99790559f077.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715601-70fb6100-edef-11e9-9b7a-7ce743a8bb3d.png)

* Should have more font weight and the arrow should be further from the text
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715607-7fe21380-edef-11e9-86ba-d6f3195a0ee8.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715620-94261080-edef-11e9-8ddd-91a9e41e540f.png)

**Comment by benzap** [comment]
Fixed in #124, closing
