### ISSUE TITLE
UI - Implement New Job Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#75]
# Desktop Preview
![](https://i.imgur.com/2EKLEVD.png)

# Mobile Preview
![](https://i.imgur.com/o31sW7X.png)

**Comment by madvas** [comment]
## Desktop
* Checkboxes are not correctly styled
Impl:
![image](https://user-images.githubusercontent.com/3857155/66197832-680ae100-e6c5-11e9-8417-280103f6108d.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66197860-735e0c80-e6c5-11e9-8d02-4bc8e3bb52ca.png)

* Whole layout is much more narrow than in designs
Impl:
![image](https://user-images.githubusercontent.com/3857155/66197982-a4d6d800-e6c5-11e9-8695-fe6c18e65171.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66197991-ab654f80-e6c5-11e9-9f2c-e51abed55736.png)

* Job Name input is not correctly styled
Impl:
![image](https://user-images.githubusercontent.com/3857155/66198004-b4562100-e6c5-11e9-8f9e-70431f44e222.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66198026-c33cd380-e6c5-11e9-97ff-341de3b5a75b.png)

* These inputs shouldn't have placeholders
* Skills should autocomplete from this [list of skills]( https://github.com/district0x/ethlance/blob/master/resources/public/edn/skills.edn)
Impl:
![image](https://user-images.githubusercontent.com/3857155/66198397-87563e00-e6c6-11e9-84c6-afe4cf9778f5.png)

* Category input is incorrectly styled
* Should say "Category", not "Select Category"
* Chevron should be pointing down when select box is not open
Impl:
![image](https://user-images.githubusercontent.com/3857155/66198562-def4a980-e6c6-11e9-841d-752c7bc3e933.png)

**Comment by benzap** [comment]
Closing tickets that were refined, having a hard time keeping track
