### ISSUE TITLE
UI - Implement My Profile Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#76]
# Desktop Preview
![](https://i.imgur.com/aFpQd1H.png)

# Mobile Preview
![](https://i.imgur.com/sdTLECi.png)

**Comment by madvas** [comment]
* Tabs should be spread throughout the whole width of underlying while panel
Impl:
![image](https://user-images.githubusercontent.com/3857155/66195897-cfbf2d00-e6c1-11e9-811c-057096053c3a.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66196140-38a6a500-e6c2-11e9-9404-aa1b8b3d4b9a.png)


* Icons should be smaller size
Impl:
![image](https://user-images.githubusercontent.com/3857155/66196100-29275c00-e6c2-11e9-8063-a62a84aa794c.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66196191-4f4cfc00-e6c2-11e9-9c54-5d29922652a9.png)

### IPhone X portrait
* Select box is overflowing
Impl:
![image](https://user-images.githubusercontent.com/3857155/66196656-1d886500-e6c3-11e9-97c1-87f5365b78d8.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66196885-8243bf80-e6c3-11e9-9511-e511acc11fe4.png)

* Side scrolling is not implemented
Impl:
![image](https://user-images.githubusercontent.com/3857155/66197150-fd0cda80-e6c3-11e9-8852-fb27018bf340.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66197162-06964280-e6c4-11e9-9029-359e37430dcd.png)

**Comment by benzap** [comment]
Work has been finished, and issues that haven't been finished were moved into #107 and #109
