### ISSUE TITLE
UI - Implement Sign Up Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#77]
# Desktop Preview
![](https://i.imgur.com/gY8Xs7g.png)

# Mobile Preview
![](https://i.imgur.com/gY8Xs7g.png)

**Comment by madvas** [comment]
* Layout should be wider
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715433-8079aa80-eded-11e9-9467-f05d32b116c7.png)
Designs:
![image](https://user-images.githubusercontent.com/3857155/66715438-925b4d80-eded-11e9-9e3b-bb8c6fa46085.png)

* Name and Professional Title are missing bottom border
* Placeholder should be different font color
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715444-9d15e280-eded-11e9-80b9-ccec74071482.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715460-bd45a180-eded-11e9-9b99-25d85080bbf8.png)

* Icon is different color than text
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715456-b4ed6680-eded-11e9-925d-c748bf497296.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715463-d0f10800-eded-11e9-9a4d-71e3b92af2a6.png)

* These inputs should not have a placeholder
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715468-e49c6e80-eded-11e9-9d0b-33a51d60b06c.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715484-13b2e000-edee-11e9-94cf-e8b0ca7dfe3f.png)

* Checkbox is different styling than designs
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715485-18779400-edee-11e9-9c3f-adbd7a1e271e.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66715488-29280a00-edee-11e9-9537-dcad93f3817c.png)

* Preferred type of payment can be removed, it'll only fixed
Impl:
![image](https://user-images.githubusercontent.com/3857155/66715505-5a083f00-edee-11e9-90d9-340affe928df.png)

**Comment by benzap** [comment]
Going to start closing issues that i've refined. Getting hard to keep track
