### ISSUE TITLE
[Feature] Escrow Service

### ISSUE THREAD

**Issue by 7flash** [district0x/ethlance#98]
![Screenshot_2019-09-16_15-58-35](https://user-images.githubusercontent.com/4569866/64942162-f3e5d600-d89a-11e9-93d1-03cb7dcd6b01.png)

Here I propose to discuss possible solutions for this problem

I would suggest to allow an option to choose custom address that is allowed to release funds in the case of dispute, - both freelancer and company should agree on this address before starting working on task.

I am able to contribute and implement proposed feature if this considered to be valid solution

@madvas @benzap

**Comment by benzap** [comment]
Hello @7flash,

The ethlance rework will make use of an triad consisting of the employer and the accepted candidate, but also an arbiter who is assigned by the employer. In situations where an employer does not pay, a dispute is raised, and the arbiter is given privileges to pay the candidate from the work contract, while acquiring a fixed rate duty.

It falls in line with what you're saying, so I appreciate that users have similar concerns.

Thank you for your input!
